name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Asegúrate de que tu rama se llame main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Inyectar Secret de Firebase
        run: |
          # Reemplaza el marcador en el index.html por el contenido del Secret
          sed -i "s/__FIREBASE_CONFIG_PLACEHOLDER__/${{ secrets.FIREBASE_CONFIG }}/g" index.html

      - name: Deploy a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Sube la carpeta raíz
          branch: gh-pages # Se publicará en esta rama
